### ISSUE TITLE
About Image Quality Performance

### ISSUE THREAD

**Issue by csguoh** [zhaominyiz/C3-STISR#6]
Hi, have a nice day! Thanks for your impressive work. Recently I was trying to reproduce your code. However, I have encountered a problem regarding image quality, i.e. PSNR and SSIM. The avg PSNR reported in the paper is **21.51 dB**, but the log below is **20.38 dB**. and the same problem is encountered with SSIM. I don't know why this is the case. I would be grateful if you could reply :D

```
evaling easy
[2022-09-05 14:25:13]	PSNR 22.13 | SSIM 0.8532	
save display images
sr_accuray_iter0: 65.60%
lr_accuray: 37.49%
hr_accuray: 76.41%
best_easy = 65.60%*
evaling medium
[2022-09-05 14:25:29]	PSNR 18.98 | SSIM 0.6449	
save display images
sr_accuray_iter0: 53.44%
lr_accuray: 21.40%
hr_accuray: 75.05%
best_medium = 54.43%
evaling hard
[2022-09-05 14:25:45]	PSNR 19.75 | SSIM 0.7125	
save display images
sr_accuray_iter0: 39.91%
lr_accuray: 21.15%
hr_accuray: 64.56%
best_hard = 39.91%*
saving best model
```

**Comment by zhaominyiz** [comment]
I have some preliminary findings on this phenomenon.
On the first hand, a better PSNR actually does not represent a better recognition ability (i.e., putting emphasis on recovering backgrounds). 
On the second, breaking the fidelity may benefit the recognition (enlarge the contrast).
If you wanna develop a C3-STISR with a higher PSNR and SSIM, you may try some tricks given in https://github.com/zhaominyiz/C3-STISR/issues/4
I will release the final pth within one week. Sorry for the late update due to the CVPR deadline.

**Comment by csguoh** [comment]
I have recently met the same problem of trade-off between fidelity and accuracy. I will try these. Thanks for your advice 👍

**Comment by zhaominyiz** [comment]
Wish you good luck! :)
Feel free to further discuss. I am really very humdrum in recent days due to the Covid19 policy :(
